# itertools.permutations(iterable[, r])
<a>Task</a> : You are given a string <em>S</em>.
Your task is to print all possible permutations of size <em>k</em> of the string in lexicographic sorted order.

<a>Input Format</a> : A single line containing the space separated string  and the integer value <em>k</em>.

In [23]:
from itertools import permutations
s,k = input().split()
print(s, k)
new_list = sorted(list(permutations(s, int(k))), reverse= False)
for word in new_list:
    print(*word, sep="")

Hac 2
Ha
Hc
aH
ac
cH
ca


# sWAP cASE
<a>Task</a> : Complete the swap_case function in the editor below.

swap_case has the following parameters: 
<li>string s: the string to modify.</li>

<a>Input Format</a> : A single line containing a string <em>s</em>.

In [ ]:
def swap_case(s):
    temp = "".join(i.upper() if i.islower() else i.lower() for i in s)
    return temp

if __name__ == '__main__':
    s = input()
    print(s)
    result = swap_case(s)
    print(result)

HacKeR
hACkEr


# Text Wrap
<a>Task</a> : Complete the wrap function in the editor below.

wrap has the following parameters:

<li>string string: a long string</li>
<li>int max_width: the width to wrap to.</li>

<a>Input Format</a> : The first line contains a string, <em>string</em>.
The second line contains the width, <em>max_width</em>.

In [ ]:
import textwrap

def wrap(string, max_width):
    return "\n".join(textwrap.wrap(string,max_width))

if __name__ == '__main__':
    string, max_width = input(), int(input())
    print(string, max_width)
    result = wrap(string, max_width)
    print(result)

Hacker Rank 3
Hac
ker
Ran
k


# Find the Runner-Up Score!
<a>Task</a> : Given the participants' score sheet for your University Sports Day, you are required to find the runner-up score. You are given  scores. Store them in a list and find the score of the runner-up.

<a>Input Format</a> : The first line contains <em>n</em>. The second line contains an array  <em>A[ ]</em> of  <em>n</em> integers each separated by a space.

In [ ]:
if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    print(sorted(set(arr))[-2])

4


# itertools.combinations()
<a>Task</a> : You are given a string <em>S</em>.
Your task is to print all possible combinations, up to size <em>k</em>, of the string in lexicographic sorted order.

<a>Input Format</a> : A single line containing the string  <em>S</em> and integer value  <em>k</em> separated by a space.

In [ ]:
from itertools import combinations

s,k = input().split()
print(s,k)
k=int(k)
i=1
while k >= i:
    words = list(combinations(sorted(s),i))
    for word in words:
        print(*word, sep="")
    i+=1

Hack 2
H
a
c
k
Ha
Hc
Hk
ac
ak
ck


# Text Alignment
<a>Task</a> : You are given a partial code that is used for generating the HackerRank Logo of variable thickness.
Your task is to replace the blank (______) with rjust, ljust or center.

<a>Input Format</a> : A single line containing the thickness value for the logo.

In [21]:
thickness = int(input()) #This must be an odd number
c = 'H'

#Top Cone
for i in range(thickness):
    print((c*i).rjust(thickness-1)+c+(c*i).ljust(thickness-1))

#Top Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))

#Middle Belt
for i in range((thickness+1)//2):
    print((c*thickness*5).center(thickness*6))    

#Bottom Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))    

#Bottom Cone
for i in range(thickness):
    print(((c*(thickness-i-1)).rjust(thickness)+c+(c*(thickness-i-1)).ljust(thickness)).rjust(thickness*6))

  H  
 HHH 
HHHHH
 HHH         HHH        
 HHH         HHH        
 HHH         HHH        
 HHH         HHH        
 HHHHHHHHHHHHHHH  
 HHHHHHHHHHHHHHH  
 HHH         HHH        
 HHH         HHH        
 HHH         HHH        
 HHH         HHH        
            HHHHH 
             HHH  
              H   


# Designer Door Mat
<a>Task</a> : Mr. Vincent works in a door mat manufacturing company. One day, he designed a new door mat with the following specifications:

Mat size must be <em>M x N </em>. (<em>N</em> is an odd natural number, and <em>M</em> is <em>3</em> times <em>N</em>.)
<li>The design should have 'WELCOME' written in the center.</li>
<li>The design pattern should only use |, . and - characters.</li> 

<a>Input Format</a> : A single line containing the the space separated values of <em>N</em> and  <em>M</em>.

In [24]:
n, m = input().split()
n = int(n)
m = int(m)
for i in range(n):
    if i < (n-1)/2:
        print((".|."*(i*2+1)).center(m, "-"))
    elif i == (n-1)/2 :
        print("WELCOME".center(m,"-"))
    elif i > (n-1)/2:
        print((".|."*((n-i)*2-1)).center(m, "-"))


------------.|.------------
---------.|..|..|.---------
------.|..|..|..|..|.------
---.|..|..|..|..|..|..|.---
----------WELCOME----------
---.|..|..|..|..|..|..|.---
------.|..|..|..|..|.------
---------.|..|..|.---------
------------.|.------------


# itertools.permutations(iterable[, r])
<a>Task</a> : You are given a string <em>S</em>.
Your task is to print all possible permutations of size <em>k</em> of the string in lexicographic sorted order.

<a>Input Format</a> : A single line containing the space separated string <em>S</em> and the integer value <em>k</em>.

In [25]:
from itertools import permutations
s,k = input().split()
new_list = sorted(list(permutations(s, int(k))), reverse= False)
for word in new_list:
    print(*word, sep="")

Ha
Hc
Hk
aH
ac
ak
cH
ca
ck
kH
ka
kc


# itertools.combinations_with_replacement(iterable, r)
<a>Task</a> : You are given a string <em>S</em>.
Your task is to print all possible size <em>k</em> replacement combinations of the string in lexicographic sorted order.

<a>Input Format</a> : A single line containing the string <em>S</em> and the integer value <em>k</em>.

In [26]:
from itertools import combinations_with_replacement

s,k = input().split()

words = list(combinations_with_replacement(sorted(s), int(k)))

for word in words:
    print(*word, sep = "")

aa
ac
ah
cc
ch
hh


# Polynomials
<a>Task</a> : You are given the coefficients of a polynomial <em>P</em>.
Your task is to find the value of <em>P</em> at point <em>x</em>.

<a>Input Format</a> : The first line contains the space separated value of the coefficients in  <em>P</em>.
The second line contains the value of <em>x</em>.

In [27]:
import numpy

t = list(map(float, input().split()))
x = int(input())
print(numpy.polyval(t,x))

12.799999999999999


# Check Strict Superset
<a>Task</a> : You are given a set  <em>A</em> and <em>n</em> other sets.
Your job is to find whether set <em>A</em> is a strict superset of each of the <em>n</em> sets.

Print True, if <em>A</em> is a strict superset of each of the <em>n</em> sets. Otherwise, print False.

<a>Input Format</a> : The first line contains the space separated elements of set  <em>A</em>.
The second line contains integer  <em>n</em>, the number of other sets.
The next  <em>n</em> lines contains the space separated elements of the other sets.

In [28]:
A = set(input().split())
n = int(input())
strict_superset = True
for i in range(n):
    new_set = set(input().split())
    if not new_set.issubset(A) or not (len(A) > len(new_set)):
        strict_superset = False
print(strict_superset)

True


# Compress the String!
<a>Task</a> : In this task, we would like for you to appreciate the usefulness of the groupby() function of itertools .
You are given a string  <em>S</em>. Suppose a character '<em>c</em>' occurs consecutively  <em>X</em> times in the string. Replace these consecutive occurrences of the character '<em>(X,c)</em>' with  in the string.

<a>Input Format</a> : A single line of input consisting of the string   <em>S</em>.

In [30]:
from itertools import groupby

s = input()
print(s)
temp_list = []
times = []

for k,g in groupby(s):
    temp_list.append(list(g))
    times.append(int(k))

for i in range(len(times)):
    print((len(temp_list[i]), times[i]), end=" ")


123456521
(1, 1) (1, 2) (1, 3) (1, 4) (1, 5) (1, 6) (1, 5) (1, 2) (1, 1) 

# Iterables and Iterators
<a>Task</a> : You are given a list of <em>N</em> lowercase English letters. For a given integer <em>K</em>, you can select any <em>K</em> indices (assume 1-based indexing) with a uniform probability from the list.

Find the probability that at least one of the <em>K</em> indices selected will contain the letter: '<em>a</em>'.

<a>Input Format</a> : The input consists of three lines. 

The first line contains the integer  <em>N</em>, denoting the length of the list.

The next line consists of <em>N</em> space-separated lowercase English letters, denoting the elements of the list.

The third and the last line of input contains the integer <em>K</em>, denoting the number of indices to be selected.

In [37]:
from itertools import permutations

l = int(input())
n = input().replace(' ', '')
k = int(input())
print([i for i in n], end=" ")
temp_list = [''.join(x) for x in permutations(n, k)]
output = 0

for i in temp_list:
    if "a" in i:
        output+=1
print("\n", output/len(temp_list))


['a', 'a', 'd', 'c'] 
 0.8333333333333334


# collections.Counter()
<a>Task</a> : <em>Raghu</em> is a shoe shop owner. His shop has <em>X</em> number of shoes.
He has a list containing the size of each shoe he has in his shop.
There are <em>N</em> number of customers who are willing to pay <em>Xi</em> amount of money only if they get the shoe of their desired size.

Your task is to compute how much money <em>Raghu</em> earned.

<a>Input Format</a> : The first line contains <em>X</em>, the number of shoes.
The second line contains the space separated list of all the shoe sizes in the shop.
The third line contains <em>N</em>, the number of customers.
The next <em>N</em> lines contain the space separated values of the <em>shoe size</em> desired by the customer and <em>Xi</em>, the price of the shoe.

In [38]:
from collections import Counter

x = int(input())
sizes = list(input().split())
n = int(input())
total_money = 0

for i in range(n):
    size, price = input().split()
    if size in Counter(sizes).keys():
        sizes.remove(size)
        total_money += int(price)
print(total_money)

200


# Company Logo
<a>Task</a> : Given a string <em>s</em>, which is the company name in lowercase letters, your task is to find the top three most common characters in the string.

<li>Print the three most common characters along with their occurrence count.
<li>Sort in descending order of occurrence count.
<li>If the occurrence count is the same, sort the characters in alphabetical order.</li>

<a>Input Format</a> : A single line of input containing the string <em>S</em>.

In [40]:
if __name__ == '__main__':
    s = input()
    new_dict = {}
    for i in s:
        if i not in new_dict.keys():
            new_dict[i] = 1
        else:
            new_dict[i] += 1
            
    new_dict = sorted(new_dict.items(), key=lambda x: (-x[1], x[0]))
            
    for i, (key,val) in enumerate(new_dict):
        if i < 3:
            print(key, val)


d 3
a 2
f 2


# Maximize It!
<a>Task</a> : You are given a function <em>f(x) = x^2</em>. You are also given <em>K</em> lists. The <em>ith</em> list consists of <em>Ni</em> elements.

You have to pick one element from each list so that the value from the equation below is maximized:

<em>S = (f(x1) + f(x2) + ... + f(xk))%M</em>

<em>X</em>denotes the element picked from the <em>ith</em> list. Find the maximized value <em>Smax</em> obtained.

<em>%</em> denotes the modulo operator.

<a>Input Format</a> : The first line contains <em>2</em> space separated integers <em>K</em> and <em>M</em>.
The next <em>K</em> lines each contains an integer <em>Ni</em>, denoting the number of elements in the <em>ith</em> list, followed by <em>Ni</em> space separated integers denoting the elements in the list.

In [54]:
from itertools import product

k, m = map(int, input().split())
n = []
max_s = []
for _ in range(k):
    temp = list(map(int, input().split()))
    temp.pop(0)
    n.append(map(lambda x: x**2%m, temp))

print(max(map(lambda x:sum(x)%m, product(*n))))

206


# Merge the Tools!
<a>Task</a> : Complete the merge_the_tools function in the editor below.

merge_the_tools has the following parameters:

<li>string s: the string to analyze</li>
<li>int k: the size of substrings to analyze</li>


<a>Input Format</a> : The first line contains a single string, <em>s</em>.
The second line contains an integer, <em>k</em>, the length of each substring. 

In [2]:
def merge_the_tools(string, k):
    # your code goes here
    for i in range(int(len(string)/k)):
        sub_string = string[i*k:(i+1)*k]    
        temp = set()
        for letter in sub_string:
            if letter not in temp:
                print(letter, end="")
                temp.add(letter)
        print()
                    
if __name__ == '__main__':
    string, k = input(), int(input())
    merge_the_tools(string, k)

ADS
AS
REF


# Alphabet Rangoli
<a>Task</a> : Complete the rangoli function in the editor below.

rangoli has the following parameters:

<li>int size: the size of the rangoli</li>

<a>Input Format</a> : Only one line of input containing  <em>size</em> , the size of the rangoli.

In [11]:
def print_rangoli(size):
    # your code goes here
    import string
    new_list =[]
    for i in range(size):
        temp = "-".join(string.ascii_letters[i:size])
        new_list.append((temp[::-1]+temp[1:]).center(2*2*(size-1)+1, "-"))
    print("\n".join(new_list[:0:-1]+new_list))
        
if __name__ == '__main__':
    n = int(input())
    print_rangoli(n)

--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------


# Capitalize!
<a>Task</a> : You are asked to ensure that the first and last names of people begin with a capital letter in their passports. For example, alison heck should be capitalised correctly as Alison Heck.

<em><span style="color:red"> *a*</span>lison <span style="color:red"> *h*</span>eck ==> Alison Heck</em>

Given a full name, your task is to capitalize the name appropriately.

<a>Input Format</a> : A single line of input containing the full name,<em>S</em>.

In [23]:
# Complete the solve function below.
def solve(s):
    temp = s.split(" ")
    return " ".join(temp[i].capitalize() for i in range(len(temp)))

if __name__ == '__main__':
    s = input()
    print(solve(s))

Sir, Chris Alan Here


# The Minion Game
<a>Task</a> : Complete the minion_game in the editor below.

minion_game has the following parameters:

<li>string string: the string to analyze</li>

<a>Input Format</a> : A single line of input containing the string <em>S</em>.

In [24]:
def minion_game(string):
    # your code goes here
    vowels = "AEIOU"
    k_score, s_score = 0, 0
    for i in range(len(string)):
        # if ith letter starting with vowels/consonants that means we can keep making words by adding
        # letters to the right until the end of string
        if string[i] in vowels:
            k_score += len(string) - i
        else:
            s_score += len(string) - i
    
    if k_score > s_score:
        print("Kevin", k_score)
    elif s_score > k_score:
        print("Stuart", s_score)
    else:
        print("Draw")
                
if __name__ == '__main__':
    s = input()
    minion_game(s)

Stuart 12


# String Formatting
<a>Task</a> : Complete the print_formatted function in the editor below.

print_formatted has the following parameters:

<li>int number: the maximum value to print</li>

<a>Input Format</a> : A single integer denoting  <em>n</em>.

In [1]:
def print_formatted(number):
    # your code goes here
    padding = len(bin(number))-2 # -2 for the 2 digit prefix 0b
    for i in range(1,number+1):
        print("{decimal:>{padding}d} {octal:>{padding}o} {HEXADECIMAL:>{padding}X} {binary:>{padding}b}".format(decimal=i,octal=i,HEXADECIMAL=i,binary=i, padding=padding))
        
if __name__ == '__main__':
    n = int(input())
    print_formatted(n)

    1     1     1     1
    2     2     2    10
    3     3     3    11
    4     4     4   100
    5     5     5   101
    6     6     6   110
    7     7     7   111
    8    10     8  1000
    9    11     9  1001
   10    12     A  1010
   11    13     B  1011
   12    14     C  1100
   13    15     D  1101
   14    16     E  1110
   15    17     F  1111
   16    20    10 10000
   17    21    11 10001


# Polar Coordinates
<a>Task</a> : You are given a complex <em>z</em>. Your task is to convert it to polar coordinates.

<a>Input Format</a> : A single line containing the complex number <em>z</em>. Note: complex() function can be used in python to convert the input as a complex number.

In [2]:
import cmath
z = complex(input())
print(abs(z), "\n", cmath.phase(z))
# below code also can be used for one of the cleanest approach
#print(*cmath.polar(complex(input())), sep='\n')

2.23606797749979 
 1.1071487177940904


# Introduction to Sets
<a>Task</a> : Complete the average function in the editor below.

average has the following parameters:

<li>int arr: an array of integers</li>

<a>Input Format</a> : The first line contains the integer, <em>N</em> , the size of <em>arr</em>.
The second line contains the <em>N</em> space-separated integers, <em>arr[i]</em>. 

In [3]:
def average(array):
    # your code goes here
    return sum(set(array)) / len(set(array))

if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)

152.25


# DefaultDict Tutorial
<a>Task</a> : In this challenge, you will be given <em>2</em> integers,  <em>n</em> and <em>m</em>. There are <em>n</em> words, which might repeat, in word group <em>A</em>. There are <em>m</em> words belonging to word group <em>B</em>. For each <em>m</em> words, check whether the word has appeared in group <em>A</em> or not. Print the indices of each occurrence of <em>m</em> in group <em>A</em>. If it does not appear, print <em>-1</em>.

<a>Input Format</a> : The first line contains integers, <em>n</em> and <em>m</em> separated by a space.
The next <em>n</em> lines contains the words belonging to group <em>A</em>.
The next <em>m</em> lines contains the words belonging to group <em>B</em>. 

In [4]:
# have been avoided solving it with multiple for loop, inspired by another solution in discussions section
from collections import defaultdict

n, m = map(int, input().split(sep=" "))
d = defaultdict(list)
for i in range(n):
    d[input()].append(str(i+1))

for _ in range(m):
    b = input()
    if b in d:
        print(' '.join(d[b]))
    else: print(-1)

1 2 4
3 5


# Calendar Module
<a>Task</a> : You are given a date. Your task is to find what the day is on that date.

<a>Input Format</a> : A single line of input containing the space separated month, day and year, respectively, in  <em>MM DD YYYYY</em>   format. 

In [5]:
import calendar

m, d, y = map(int, input().split(sep=" "))

print(calendar.day_name[calendar.weekday(year=y, month=m, day=d)].upper())

WEDNESDAY


# Exceptions
<a>Task</a> : You are given two values <em>a</em> and <em>b</em>.
Perform integer division and print <em>a/b</em>.

<a>Input Format</a> : The first line contains <em>T</em>, the number of test cases.
The next <em>T</em> lines each contain the space separated values of <em>a</em> and <em>b</em>.



In [6]:
t = int(input())
for _ in range(t):
    try:
        a,b = map(int, input().split(sep=" "))
        print(a//b)
    except Exception as exception:
        print("Error Code:", exception)

5
Error Code: invalid literal for int() with base 10: 'a'
Error Code: integer division or modulo by zero


# Time Delta
<a>Task</a> : You are given two timestamps of one such post that a user can see on his newsfeed in the following format:

<em>Day dd Mon yyyy hh:mm:ss +xxxx</em>

Here +xxxx represents the time zone. Your task is to print the absolute difference (in seconds) between them.

<a>Input Format</a> : The first line contains <em>T</em>, the number of testcases.
Each testcase contains <em>2</em> lines, representing time <em>t1</em> and time <em>t2</em>.



In [8]:
from datetime import datetime, timedelta

# Complete the time_delta function below.
def time_delta(t1, t2):
    input_format = "%a %d %b %Y %H:%M:%S %z"

    return int(abs(datetime.strptime(t1, input_format)-datetime.strptime(t2, input_format)).total_seconds())

if __name__ == '__main__':
    t = int(input())
    for t_itr in range(t):
        t1 = input()

        t2 = input()

        print(time_delta(t1, t2))


25200
88200


# Find Angle MBC
<a>Task</a> : You are given the lengths <em>AB</em> and <em>BC</em>.
Your task is to find <em>MBC</em> (angle <em>Teta</em>) in degrees.

<a>Input Format</a> : The first line contains the length of side <em>AB</em>.
The second line contains the length of side <em>BC</em>.



In [10]:
from math import atan, degrees

ab = int(input())
bc = int(input())

print(str(round(degrees(atan(ab/bc)))) +u'\N{DEGREE SIGN}')

37°


# No Idea!
<a>Task</a> : There is an array of <em>n</em> integers. There are also <em>2 disjoint sets</em>, <em>A</em> and <em>B</em>, each containing <em>m</em> integers. You like all the integers in set <em>A</em> and dislike all the integers in set <em>B</em>. Your initial happiness is <em>0</em>. For each <em>i</em> integer in the array, if <em>i in A</em>, you add <em>1</em> to your happiness. If <em>i in B</em>, you add <em>-1</em> to your happiness. Otherwise, your happiness does not change. Output your final happiness at the end.

Note: Since <em>A</em> and <em>B</em> are sets, they have no repeated elements. However, the array might contain duplicate elements.

<a>Input Format</a> : The first line contains integers <em>n</em> and <em>m</em> separated by a space.
The second line contains <em>n</em> integers, the elements of the array.
The third and fourth lines contain <em>m</em> integers, <em>A</em> and <em>B</em>, respectively.



In [11]:
n,m = map(int, input().split(sep= " "))
happiness = 0
array = list(map(int, input().split(sep=" ")))
A = set(map(int, input().split(sep=" ")))
B = set(map(int, input().split(sep=" ")))

for i in array:
    if i in A:
        happiness +=1
    if i in B:
        happiness -=1
print(happiness)

1


# Incorrect Regex
<a>Task</a> : You are given a string <em>S</em>.
Your task is to find out whether <em>S</em> is a valid regex or not.

<a>Input Format</a> : The first line contains integer <em>T</em>, the number of test cases.
The next <em>T</em> lines contains the string <em>S</em>.

In [1]:
import re

t = int(input())

for _ in range(t):
    pattern = str(input())
    try:
        re.compile(pattern)
        print(True)
    except Exception:
        print(False)

True
False


# Collections.namedtuple()
<a>Task</a> : Dr. John Wesley has a spreadsheet containing a list of student's <em>IDs</em>, <em>marks</em>, <em>class</em> and <em>name</em>.

Your task is to help Dr. Wesley calculate the average marks of the students.
<em>AVERAGE = Sum of all marks / Total Students</em>

Note:
<li>1. Columns can be in any order. IDs, marks, class and name can be written in any order in the spreadsheet.</li>
<li>2. Column names are ID, MARKS, CLASS and NAME. (The spelling and case type of these names won't change.)</li>

<a>Input Format</a> : The first line contains an integer <em>N</em>,, the total number of students.
The second line contains the names of the columns in any order.
The next <em>N</em>, lines contains the <em>marks</em>, <em>IDs</em>, <em>name</em> and <em>class</em>, under their respective column names.

In [2]:
from collections import namedtuple

n = int(input())
Student = namedtuple('Student', list(input().split()))
sum_marks = 0

for _ in range(n):
    student = Student(*input().split())
    sum_marks += int(student.MARKS)

print(sum_marks/n)

78.0


# Collections.OrderedDict()
<a>Task</a> : You are the manager of a supermarket.
You have a list of <em>N</em> items together with their prices that consumers bought on a particular day.
Your task is to print each item_name and net_price in order of its first occurrence.

item_name = Name of the item.

net_price = Quantity of the item sold multiplied by the price of each item.

<a>Input Format</a> : The first line contains the number of items, <em>N</em>.
The next <em>N</em> lines contains the item's name and price, separated by a space.

In [3]:
from collections import OrderedDict

ordered_dict = OrderedDict()
for _ in range(int(input())):
    temp = input()
    name = " ".join(temp.split()[:-1])
    price = int(temp.split()[-1])
    if name in ordered_dict.keys():
        ordered_dict[name] += price
    else:
        ordered_dict[name] = price

for key, val in ordered_dict.items():
    print(key, val)

BANANA FRIES 12
POTATO CHIPS 60
APPLE JUICE 20
CANDY 20


# Symmetric Difference
<a>Task</a> : Given <em>2</em> sets of integers, <em>M</em> and <em>N</em>, print their symmetric difference in ascending order. The term symmetric difference indicates those values that exist in either  <em>M</em> or <em>N</em>  but do not exist in both.

<a>Input Format</a> : The first line of input contains an integer, <em>M</em>.
The second line contains <em>M</em> space-separated integers.
The third line contains an integer, <em>N</em>.
The fourth line contains <em>M</em> space-separated integers.

In [1]:
m = int(input()) #number of elements in first set
m_set = set(map(int, input().split())) #first set elements
n = int(input()) #number of elements in second set
n_set = set(map(int, input().split())) #second set elements

#values which exist in first set but not in second set
diff_m = m_set.difference(n_set) 

#values which exist in second set but not in first set
diff_n = n_set.difference(m_set) 

#print out symmetric difference by joining them with new line
print("\n".join(str(i) for i in sorted(diff_m.union(diff_n))))

5
9
11
12


# Set .add()
<a>Task</a> : Apply your knowledge of the .add() operation to help your friend Rupal.

Rupal has a huge collection of country stamps. She decided to count the total number of distinct country stamps in her collection. She asked for your help. You pick the stamps one by one from a stack of <em>N</em> country stamps.

Find the total number of distinct country stamps.

<a>Input Format</a> : The first line contains an integer <em>N</em>, the total number of country stamps.
The next <em>N</em> lines contains the name of the country where the stamp is from.

In [2]:
n = int(input()) #total number of stamps
temp = set() #temporary set

for _ in range(n): 
    temp.add(input()) #add every single country name to set

#print out total number of country
print(len(temp)) 

5


# Set .discard(), .remove() & .pop()
<a>Task</a> : You have a non-empty set <em>s</em>, and you have to execute <em>N</em> commands given in <em>N</em> lines.

The commands will be pop, remove and discard.

<a>Input Format</a> : The first line contains integer <em>n</em>, the number of elements in the set <em>s</em>.
The second line contains <em>n</em> space separated elements of set <em>s</em>. All of the elements are non-negative integers, less than or equal to 9.
The third line contains integer <em>N</em>, the number of commands.
The next <em>N</em> lines contains either pop, remove and/or discard commands followed by their associated value.

In [3]:
n = int(input()) #number of elements in the set s
s = set(map(int, input().split())) #space separated elements of set

#loop in range number of commands
for _ in range(int(input())): 
    temp = input() #assign input a temporary variable
    command = temp.split()[0] #assign command to variable 
    #if the command is not "pop" get associated value and execute the command
    if command != "pop":
        value = int(temp.split()[-1])
        eval('s.{0}({1})'.format(command, value)) #eval() function is new for me, it is useful to dynamically evaluate expressions 
    else:
        eval('s.{0}()'.format(command)) #pop command only

#print out sum of the set, after completing all operations on the set 
print(sum(s))

18


# Set .union() Operation
<a>Task</a> : The students of District College have subscriptions to English and French newspapers. Some students have subscribed only to English, some have subscribed to only French and some have subscribed to both newspapers.

You are given two sets of student roll numbers. One set has subscribed to the English newspaper, and the other set is subscribed to the French newspaper. The same student could be in both sets. Your task is to find the total number of students who have subscribed to at least one newspaper.

<a>Input Format</a> : The first line contains an integer,<em>n</em>, the number of students who have subscribed to the English newspaper.

The second line contains <em>n</em> space separated roll numbers of those students.

The third line contains <em>b</em>, the number of students who have subscribed to the French newspaper.

The fourth line contains <em>b</em> space separated roll numbers of those students.

In [4]:
n = int(input()) #number of student who have subscribed to the English newspaper
set_n = set(map(int, input().split())) #roll numbers of those students
b = int(input()) #number of student who have subscribed to the French newspaper
set_b = set(map(int, input().split())) #roll numbers of those students

#print out total number of students who have subscribed to at least one newspaper
print(len(set_n.union(set_b)))

8


# Set .intersection() Operation
<a>Task</a> : The students of District College have subscriptions to English and French newspapers. Some students have subscribed only to English, some have subscribed only to French, and some have subscribed to both newspapers.

You are given two sets of student roll numbers. One set has subscribed to the English newspaper, one set has subscribed to the French newspaper. Your task is to find the total number of students who have subscribed to both newspapers.

<a>Input Format</a> : The first line contains an integer,<em>n</em>, the number of students who have subscribed to the English newspaper.

The second line contains <em>n</em> space separated roll numbers of those students.

The third line contains <em>b</em>, the number of students who have subscribed to the French newspaper.

The fourth line contains <em>b</em> space separated roll numbers of those students.

In [5]:
n = int(input()) #number of student who have subscribed to the English newspaper
set_n = set(map(int, input().split())) #roll numbers of those students
b = int(input()) #number of student who have subscribed to the French newspaper
set_b = set(map(int, input().split())) #roll numbers of those students

#print out total number of students who have subscribed to both newspaper
print(len(set_n.intersection(set_b)))

6


# Set .difference() Operation
<a>Task</a> : The students of District College have subscriptions to English and French newspapers. Some students have subscribed only to English, some have subscribed only to French, and some have subscribed to both newspapers.

You are given two sets of student roll numbers. One set has subscribed to the English newspaper, and one set has subscribed to the French newspaper. Your task is to find the total number of students who have subscribed to only English newspapers.

<a>Input Format</a> : The first line contains an integer,<em>n</em>, the number of students who have subscribed to the English newspaper.

The second line contains <em>n</em> space separated roll numbers who have subscribed to the English newspaper.

The third line contains <em>b</em>, the number of students who have subscribed to the French newspaper.

The fourth line contains <em>b</em> space separated roll numbers who have subscribed to the French newspaper.

In [6]:
n = int(input()) #number of student who have subscribed to the English newspaper
set_n = set(map(int, input().split())) #roll numbers of those students
b = int(input()) #number of student who have subscribed to the French newspaper
set_b = set(map(int, input().split())) #roll numbers of those students

#print out total number of students who have subscribed to only English newspapers. 
print(len(set_n.difference(set_b)))

0


# Set .symmetric_difference() Operation
<a>Task</a> : The students of District College have subscriptions to English and French newspapers. Some students have subscribed only to English, some have subscribed only to French, and some have subscribed to both newspapers.

You are given two sets of student roll numbers. One set has subscribed to the English newspaper, and one set has subscribed to the French newspaper. Your task is to find the total number of students who have subscribed to either the English or the French newspaper but not both.

<a>Input Format</a> : The first line contains an integer,<em>n</em>, the number of students who have subscribed to the English newspaper.

The second line contains <em>n</em> space separated roll numbers who have subscribed to the English newspaper.

The third line contains <em>b</em>, the number of students who have subscribed to the French newspaper.

The fourth line contains <em>b</em> space separated roll numbers who have subscribed to the French newspaper.

In [7]:
n = int(input()) #number of student who have subscribed to the English newspaper
set_n = set(map(int, input().split())) #roll numbers of those students
b = int(input()) #number of student who have subscribed to the French newspaper
set_b = set(map(int, input().split())) #roll numbers of those students

#print out total number of students who have subscribed to either the English or the French newspaper but not both
print(len(set_n.symmetric_difference(set_b)))

4


# Set Mutations
<a>Task</a> : You are given a set <em>A</em> and <em>N</em> number of other sets. These <em>N</em> number of sets have to perform some specific mutation operations on set <em>A</em>.

Your task is to execute those operations and print the sum of elements from set <em>A</em>.

<a>Input Format</a> : The first line contains the number of elements in set <em>A</em>.
The second line contains the space separated list of elements in set <em>A</em>.

The third line contains integer <em>N</em>, the number of other sets.

The next <em>2 * N</em> lines are divided into <em>N</em> parts containing two lines each.

The first line of each part contains the space separated entries of the operation name and the length of the other set.

The second line of each part contains space separated list of elements in the other set.

In [8]:
n = int(input()) #number of elements in the set A
A = set(map(int, input().split())) #space separated elements of set

#loop in range number of commands
for _ in range(int(input())): 
    command = input().split()[0] #assign command to variable, size of upcoming set is meaningless
    temp_set =  set(map(int, input().split())) #assign inputted set to a temporary variable
    eval('A.{0}({1})'.format(command, temp_set)) #dynamically evaluate expressions 

#print out sum of the set, after completing all operations on the set 
print(sum(A))

38


# The Captain's Room
<a>Task</a> : Mr. Anant has an unordered list of randomly arranged room entries. The list consists of the room numbers for all of the tourists. The room numbers will appear <em>K</em> times per group except for the Captain's room.

Mr. Anant needs you to help him find the Captain's room number.
The total number of tourists or the total number of groups of families is not known to you.
You only know the value of <em>K</em> and the room number list.

<a>Input Format</a> : The first line consists of an integer, <em>K</em>, the size of each group.
The second line contains the unordered elements of the room number list.


In [11]:
#have found this solution on discussions, it has far better time complexity than my solution

k = int(input()) #group size
rooms = list(map(int, input().split())) #unordered elements of the room numbers
myset = set(rooms) #create set from rooms list

#basically "k times sum of individual room numbers" difference "sum of 1 times captain's room and k times other room numbers" / k-1
print(((sum(myset) * k) - sum(rooms))//(k-1))

8


# Python Evaluation
<a>Task</a> :You are given an expression in a line. Read that line as a string variable, such as var, and print the result using eval(var).

<a>Sample Input</a> : print(2 + 3)


In [1]:
var = input()   #input expression
eval(var)   #evaluate expression

7


# Athlete Sort
<a>Task</a> : You are given a spreadsheet that contains a list of <em>N</em> athletes and their details (such as age, height, weight and so on). You are required to sort the data based on the <em>K</em>th attribute and print the final resulting table.

<a>Input Format</a> : The first line contains <em>N</em> and <em>M</em> separated by a space.
The next <em>N</em> lines each contain <em>M</em> elements.
The last line contains <em>K</em>.


In [2]:
if __name__ == '__main__':
    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    k = int(input())
    #until here code was already added  

    arr.sort(key=lambda row: (row[k]))  #sort the list based on Kth attribute 
    for rows in (arr):
        print(*rows)    #print rows in the list

7 1 0
10 2 5
6 5 9
9 9 9
1 23 12


# Any or All
<a>Task</a> : You are given a space separated list of integers. If all the integers are positive, then you need to check if any integer is a palindromic integer.

<a>Input Format</a> : The first line contains an integer <em>N</em>. <em>N</em> is the total number of integers in the list.
The second line contains the space separated list of <em>N</em> integers.

In [4]:
n = int(input())    #total number of integers in list
arr = list(input().split()) #list of integers

#print true if (all elements are positive) and (any of elements are palindromic integer)
print(all([int(i)>0 for i in arr]) and any([j == j[::-1] for j in arr]))
#palindromic integer means that an integer equals to reverse of itself e.g., 151, 2002, 5 etc.

True
9 9
5 5


# ginortS
<a>Task</a> : Your task is to sort the string <em>S</em> in the following manner:

<li>All sorted lowercase letters are ahead of uppercase letters.</li>
<li>All sorted uppercase letters are ahead of digits.</li>
<li>All sorted odd digits are ahead of sorted even digits.</li>

<a>Input Format</a> : A single line of input contains the string <em>S</em>.

In [6]:
s = input() #input string
lower, upper, even, odd = [],[],[],[]   #list method preferred to solve problem

for i in s:
    if i.isalpha(): #if the element is a letter
        lower.append(i) if i.islower() else upper.append(i) #if i is a lowercase letter then append it to lower list, and vice versa
    elif i.isdigit():   #if the element is a digit
        even.append(i) if int(i) % 2 ==0 else odd.append(i) #if i is a even integer then append it to even list, and vice versa

#print out all lists in proper sort
print(*sorted(lower), *sorted(upper), *sorted(odd), *sorted(even), sep="")

ginortS1324


# Shape and Reshape
<a>Task</a> : You are given a space separated list of nine integers. Your task is to convert this list into a <em>3 X 3</em> NumPy array.

<a>Input Format</a> : A single line of input containing  <em>9</em> space separated integers.

In [7]:
import numpy as np

arr = np.array(input().split(), int)     #convert input into numpy array

print(np.reshape(arr,(3,3)))    #reshape the array and print it out

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Transpose and Flatten
<a>Task</a> : You are given a <em>N</em>x<em>M</em> integer array matrix with space separated elements (<em>N</em>= rows and  <em>M</em>= columns).
Your task is to print the transpose and flatten results.

<a>Input Format</a> : The first line contains the space separated values of <em>N</em> and <em>M</em>.
The next <em>N</em> lines contains the space separated elements of <em>M</em> columns.

In [8]:
import numpy as np

n,m = map(int, input().split()) #input row and col numbers
arr = []    #list method preferred to solve problem
for _ in range(n):
    arr.append(list(input().split()))   #append inputs as rows
arr = np.asarray_chkfinite(arr,int)     #convert list to numpy array

#print out transpose and flatten of array
print(np.transpose(arr), arr.flatten(), sep="\n")

[[1 3]
 [2 4]]
[1 2 3 4]


# Concatenate
<a>Task</a> : You are given two integer arrays of size <em>N</em>x<em>P</em> and <em>M</em>x<em>P</em> (<em>N</em> & <em>M</em> are rows, and <em>P</em> is the column). Your task is to concatenate the arrays along axis <em>0</em>.

<a>Input Format</a> : The first line contains space separated integers <em>N</em>, <em>M</em> and <em>P</em>.
The next <em>N</em> lines contains the space separated elements of the <em>P</em> columns.
After that, the next <em>M</em> lines contains the space separated elements of the <em>P</em> columns.

In [ ]:
import numpy as np

n,m,p = map(int, input().split())
arr1, arr2 = [],[]

for _ in range(n):
    arr1.append(list(input().split()))
for _ in range(m):
    arr2.append(list(input().split()))

print(np.concatenate((np.asarray_chkfinite(arr1, int), np.asarray_chkfinite(arr2, int)), axis=0))

# Zeros and Ones
<a>Task</a> : You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

<a>Input Format</a> : A single line containing the space-separated integers.

In [1]:
import numpy as np

arr = tuple(map(int, input().split())) #creadting tuple from input

print(np.zeros((arr),dtype=int)) #printing out zeros
print(np.ones((arr),dtype=int)) #printing out ones

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# Concatenate
<a>Task</a> : You are given two integer arrays of size <em>N</em>x<em>P</em> and <em>M</em>x<em>P</em> (<em>N</em> & <em>M</em> are rows, and <em>P</em> is the column). Your task is to concatenate the arrays along axis <em>0</em>.

<a>Input Format</a> : The first line contains space separated integers <em>N</em>, <em>M</em> and <em>P</em>.
The next <em>N</em> lines contains the space separated elements of the <em>P</em> columns.
After that, the next <em>M</em> lines contains the space separated elements of the <em>P</em> columns.